CREATE TABLE USER_TOKENS (
   ID SERIAL PRIMARY KEY,
   EMAIL VARCHAR(100),
   REFRESH_TOKEN VARCHAR(500),
   ACCESS_TOKEN VARCHAR(500),
   UNIQUE (EMAIL)
);


CREATE TABLE USER_LAST_UPDATES (
   EMAIL VARCHAR(100) PRIMARY KEY,
   LAST_UPDATE_SHORT_TERM DATE,
   LAST_UPDATE_MEDIUM_TERM DATE,
   LAST_UPDATE_LONG_TERM DATE
)